export const button = {
	primary: `
    font-manrope
    h-[5.5rem]
    bg-green
    border-green
    border-[0.2rem]
    items-center
    justify-center
    text-darkpurple
    text-[1.6rem]
    font-bold
    leading-[3.2rem]
    z-[99]
    hover:bg-darkpurple
    hover:text-green
    lg:text-[1.8rem]
    lg:h-[6.1rem]
  `,
	secondary: `
      bg-transparent
      font-manrope
      font-bold
      w-[12.4rem]
      h-[3.4rem]
      text-[1.6rem]
      leading-[3.2rem]
      tracking-[-0.016rem]
      text-white
      flex 
      justify-center 
      items-end 
      border-b-[0.3rem]
      z-[99]
      border-green
      hover:text-green
      lg:text-[1.8rem]
      lg:w-[14rem]
    `,
};
